/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OnlineChat;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vinay
 */
public class SelectThread extends javax.swing.JFrame {

    String Author = "";

    /**
     * Creates new form ViewThread
     */
    public SelectThread() {
        initComponents();
    }

    public SelectThread(String User) {
        initComponents();
        String Use;
        Use = User;
        System.out.println(Use);
        UserLog.setText(Use);

    }

    /**
     * This me static void main(String user) { throw new
     * UnsupportedOperationException("Not supported yet."); //To change body of
     * generated methods, choose Tools | Templates. }
     *
     * thod is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        ViewThread = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        EditThread = new javax.swing.JButton();
        AddThread = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        LogOut = new javax.swing.JButton();
        UserLog = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));

        ViewThread.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title", "Last Edited", "Author"
            }
        ));
        jScrollPane4.setViewportView(ViewThread);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 109, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Online Chat Main Page");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        EditThread.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EditThread.setText("Add Message");
        EditThread.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditThreadActionPerformed(evt);
            }
        });
        jPanel2.add(EditThread, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 525, 130, -1));

        AddThread.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AddThread.setText("Add Thread");
        AddThread.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddThreadActionPerformed(evt);
            }
        });
        jPanel2.add(AddThread, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 530, -1, -1));

        jLabel2.setText("Welcome to online chat. Please add a new thread to start a conversation or click on the thread which you want to edit and select Edit Button");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 64, -1, -1));

        LogOut.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LogOut.setText("Log Out");
        LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutActionPerformed(evt);
            }
        });
        jPanel2.add(LogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(629, 525, -1, -1));
        jPanel2.add(UserLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 120, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Logged in as:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 842, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditThreadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditThreadActionPerformed
        // TODO add your handling code here:
        Boolean editing = false;
        String title = "";
        int row = ViewThread.getSelectedRow();
        System.out.println(row);
        if (row != -1) {
            String tt = ViewThread.getModel().getValueAt(row, 0).toString();
            
            java.util.List<threadserver.UserThread> listOfThreads = getThreads();

            for (int i = 0; i < listOfThreads.size(); i++) {
                if (listOfThreads.get(i).getTitle().equals(tt)) {
                    setisEditing(listOfThreads.get(i).getTitle());
                    saveThreads();
                    System.out.println(getThreads().get(i).isIsEditing());
                    break;

                }
            }
            String User = UserLog.getText();
            new EditThread(User, editing, title).setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Please select a thread to add message");
        }
    }//GEN-LAST:event_EditThreadActionPerformed

    private void AddThreadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddThreadActionPerformed
        // TODO add your handling code here:
        this.dispose();
        String User = UserLog.getText();
        new AddThread(User).setVisible(true);

    }//GEN-LAST:event_AddThreadActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here
        UserLog.setEditable(false);
        DefaultTableModel model = (DefaultTableModel) ViewThread.getModel();
        int numOfThreads = getNumOfThreads();
        for (int i = 0; i < numOfThreads; i++) {
            Object[] row = getThreadInfo(i).toArray();
            model.addRow(row);
        }
    }//GEN-LAST:event_formWindowOpened

    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        LoginPage LoginPage = new LoginPage();
        LoginPage.setVisible(true);
    }//GEN-LAST:event_LogOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectThread.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectThread.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectThread.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectThread.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new SelectThread().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddThread;
    private javax.swing.JButton EditThread;
    private javax.swing.JButton LogOut;
    private javax.swing.JTextField UserLog;
    private javax.swing.JTable ViewThread;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables

    private static void saveThreads() {
        threadserver.ThreadService_Service service = new threadserver.ThreadService_Service();
        threadserver.ThreadService port = service.getThreadServicePort();
        port.saveThreads();
    }

    private static java.util.List<threadserver.UserThread> getThreads() {
        threadserver.ThreadService_Service service = new threadserver.ThreadService_Service();
        threadserver.ThreadService port = service.getThreadServicePort();
        return port.getThreads();
    }

    private static Integer getNumOfThreads() {
        threadserver.ThreadService_Service service = new threadserver.ThreadService_Service();
        threadserver.ThreadService port = service.getThreadServicePort();
        return port.getNumOfThreads();
    }

    private static java.util.List<java.lang.Object> getThreadInfo(java.lang.Integer i) {
        threadserver.ThreadService_Service service = new threadserver.ThreadService_Service();
        threadserver.ThreadService port = service.getThreadServicePort();
        return port.getThreadInfo(i);
    }

    private static String setisEditing(java.lang.String edit) {
        threadserver.ThreadService_Service service = new threadserver.ThreadService_Service();
        threadserver.ThreadService port = service.getThreadServicePort();
        return port.setisEditing(edit);
    }

}
